include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    require_trailing_commas: true
    prefer_single_quotes: false
    avoid_print: true
    prefer_const_constructors: true
    use_key_in_widget_constructors: true
